/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: blackwind191121 (https://sketchfab.com/blackwind191121)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-board-2557ab6898ac47ba9bfdfdb607454825
Title: black_board
*/

import { Text, useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

interface IBlackBoardProps {
    text?: string;
}

export const BlackBoard = ({ text }: IBlackBoardProps) => {
    const model = useGLTF("/models/props/black_board.glb") as GLTFResult;

    return (
        <>
            <primitive object={model.scene} scale={0.009} position={[ -20.734, 1, -2 ]} rotation={[ 0, Math.PI / 2, 0 ]} />
            <Text
                font="/fonts/whatever-it-takes.ttf"
                scale={ 0.5 }
                maxWidth={ 0.25 }
                lineHeight={ 0.75 }
                position={[ -20.769, 1.5, -1.7 ]}
                rotation={ [ 0, Math.PI / 2, 0 ] }
            >
                {text}
                <meshBasicMaterial toneMapped={ false } />
            </Text>
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        defaultMaterial: Mesh;
        defaultMaterial_1: Mesh;
        defaultMaterial_2: Mesh;
        defaultMaterial_3: Mesh;
        defaultMaterial_4: Mesh;
    };
    materials: {
        Material__33: MeshStandardMaterial;
        Material__34: MeshStandardMaterial;
        Material__30: MeshStandardMaterial;
        Material__31: MeshStandardMaterial;
        Material__24: MeshStandardMaterial;
    };
};

useGLTF.preload("/models/props/black_board.glb");
