/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Riley Queen (https://polyhaven.com/all?a=Riley%20Queen)
License: CC0 (https://polyhaven.com/license)
Source: https://polyhaven.com/a/chess_set
Title: Chess Set
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

import { IAnomalyProps } from "@/models/props/props-interface";
import useGame from "@/store/useGame";

export const ChessSet = ({ isAnomaly, anomalyType }: IAnomalyProps) => {
    const { difficulty } = useGame();

    const model = useGLTF("/models/props/chess_set.glb") as GLTFResult;

    const isAnomalyMedium1 = isAnomaly && difficulty === "medium" && anomalyType === 1;

    return (
        <>
            <primitive object={model.scene} position={[ -10.7, 0.45, -2.5 ]} rotation={[ 0, isAnomalyMedium1 ? Math.PI / 3 : -Math.PI / 1.5, 0 ]} scale={0.9} />
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        piece_rook_white_01: Mesh;
        board: Mesh;
        piece_rook_black_01: Mesh;
    };
    materials: {
        chess_set_pieces_white: MeshStandardMaterial;
        chess_set_board: MeshStandardMaterial;
        chess_set_pieces_black: MeshStandardMaterial;
    };
};

useGLTF.preload("/models/props/chess_set.glb");
