/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mtcollings (https://sketchfab.com/mtcollings)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/antique-globe-78b47132c6be42bcb664545a69b380d9
Title: Antique Globe
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

export const Globe = () => {
    const model = useGLTF("/models/props/globe.glb") as GLTFResult;

    return (
        <>
            <primitive object={ model.scene } position={ [ -19.8, 0.67, -1.4 ] } rotation={ [ 0, Math.PI / 4, 0 ] } />
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        Globe_Base_low001_Globe_Base_0: Mesh;
        Globe_low001_Globe003_0: Mesh;
    };
    materials: {
        Globe_Base: MeshStandardMaterial;
        ["Globe.003"]: MeshStandardMaterial;
    };
};

useGLTF.preload("/models/props/globe.glb");
