/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sean Buckley (https://polyhaven.com/all?a=Sean%20Buckley)
License: CC0 (https://polyhaven.com/license)
Source: https://polyhaven.com/a/street_rat
Title: Street Rat
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

export const Rat = () => {
    const model = useGLTF("/models/props/rat.glb") as GLTFResult;

    return (
        <>
            <primitive object={model.scene} position={[ 0.8, -0.526, 2.6 ]} rotation={[ 0, Math.PI / 1.2, 0 ]} scale={3} />
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        street_rat: Mesh;
    };
    materials: {
        street_rat: MeshStandardMaterial;
    };
};

useGLTF.preload("/models/props/rat.glb");
