/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kroko.blend (https://sketchfab.com/jaromir.ternavskiy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/school-hat-8b5b2609abd14c5fba58d53aeebfdaeb
Title: School Hat
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

export const SchoolHat = () => {
    const model = useGLTF("/models/props/school_hat.glb") as GLTFResult;

    return (
        <>
            <primitive object={model.scene} scale={0.065} position={[ -26.35, -0.45, 1.2 ]} rotation={[ 0, Math.PI / 2.2, 0 ]} />
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        Cylinder_Material001_0: Mesh;
        Sphere__0: Mesh;
        Sphere001_Material002_0: Mesh;
        Cylinder001_Material003_0: Mesh;
    };
    materials: {
        ["Material.001"]: MeshStandardMaterial;
        Sphere__0: MeshStandardMaterial;
        ["Material.002"]: MeshStandardMaterial;
        ["Material.003"]: MeshStandardMaterial;
    };
};

useGLTF.preload("/models/props/school_hat.glb");
