/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: barism09 (https://sketchfab.com/barism09)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/school-desk-a74180ee97bb4917b24cd48580663b44
Title: School Desk
*/

import { Clone, useGLTF } from "@react-three/drei";
import React, { useMemo, useRef } from "react";
import { Group, Mesh, MeshStandardMaterial, Vector3 } from "three";
import { GLTF } from "three-stdlib";

export const SchoolDeskAnomaly = (props: React.JSX.IntrinsicElements["group"]) => {
    const { nodes, materials } = useGLTF("/models/props/school_desk.glb") as GLTFResult;

    return (
        <group {...props} dispose={null} scale={0.01} rotation={[ 0, 0.82, 0 ]}>
            <group rotation={[ -Math.PI / 2, 0, -2.39 ]}>
                <group rotation={[ Math.PI / 2, 0, 0 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.defaultMaterial.geometry} material={materials.ChackerMat} />
                    <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_1.geometry} material={materials.ChackerMat} />
                    <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_2.geometry} material={materials.ChackerMat} />
                    <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_3.geometry} material={materials.ChackerMat} />
                </group>
            </group>
        </group>
    );
};

export const SchoolDesk = () => {
    const model = useGLTF("/models/props/school_desk.glb") as GLTFResult;

    const deskRef = useRef<Group>(null);

    const positions = useMemo(() => {
        return [
            new Vector3(2.2, -0.56, -3.3),
            new Vector3(2.2, -0.56, -1.2),
            new Vector3(0.2, -0.56, -3.4),
            new Vector3(0.2, -0.56, -1.3),
            new Vector3(-2.1, -0.56, -1.3),
            new Vector3(-2.2, -0.56, -3.3),
            new Vector3(-4.2, -0.56, -3.4),
            new Vector3(-4.2, -0.56, -1.3),
            new Vector3(-6.2, -0.56, -3.5),
            new Vector3(-6.2, -0.56, -2.3),
            new Vector3(-6.2, -0.56, -1.1),
            new Vector3(-8.2, -0.56, -3.5),
            new Vector3(-8.2, -0.56, -2.3),
            new Vector3(-8.2, -0.56, -1.1),
            new Vector3(-10.2, -0.56, -3.5),
            new Vector3(-10.2, -0.56, -2.3),
            new Vector3(-10.2, -0.56, -1.1),
            new Vector3(-12.25, -0.56, -3.25),
            new Vector3(-12.1, -0.56, -1.35),
            new Vector3(-14.2, -0.56, -3.3),
            new Vector3(-14.2, -0.56, -1.3),
        ];
    }, []);

    return (
        <>
            {positions.map((position, index) => (
                <Clone key={index} ref={deskRef} object={model.scene} scale={0.01} rotation={[ 0, 0.82, 0 ]} position={position} />
            ))}
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        defaultMaterial: Mesh;
        defaultMaterial_1: Mesh;
        defaultMaterial_2: Mesh;
        defaultMaterial_3: Mesh;
    };
    materials: {
        ChackerMat: MeshStandardMaterial;
    };
};

useGLTF.preload("/models/props/school_desk.glb");
