/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kroko.blend (https://sketchfab.com/jaromir.ternavskiy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/school-diary-2bc1d870be71432581735272757d7e03
Title: School Diary
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

export const SchoolDiary = () => {
    const model = useGLTF("/models/props/school_diary.glb") as GLTFResult;

    return (
        <>
            <primitive object={ model.scene } position={ [ -4.7, 0.454, -3.3 ] } scale={ 0.15 } rotation={ [ 0, Math.PI / 15, 0 ] } />
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        Plane_Material_0: Mesh;
        Plane001_Material001_0: Mesh;
        Plane002_Material002_0: Mesh;
        Plane010_Material004_0: Mesh;
        Cylinder__0: Mesh;
        Plane003_Material003_0: Mesh;
    };
    materials: {
        Material: MeshStandardMaterial;
        ["Material.001"]: MeshStandardMaterial;
        ["Material.002"]: MeshStandardMaterial;
        ["Material.004"]: MeshStandardMaterial;
        Cylinder__0: MeshStandardMaterial;
        ["Material.003"]: MeshStandardMaterial;
    };
};

useGLTF.preload("/models/props/school_diary.glb");
