/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: cig3d (https://sketchfab.com/cig3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/teachers-desk-9ee8608e76704de7aa67d022c81e42cc
Title: Teachers Desk
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

export const TeacherDesk = () => {
    const model = useGLTF("/models/props/teachers_desk.glb") as GLTFResult;

    return (
        <>
            <primitive object={ model.scene } rotation={ [ 0, -Math.PI / 2, 0 ] } position={ [ -19.4, -0.54, -1.22 ] } />
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        Teacher_Desk_mat_leg_main_0: Mesh;
        Teacher_Desk_mat_leg_foot_0: Mesh;
        Teacher_Desk_mat_table_black_0: Mesh;
        Teacher_Desk_mat_table_wood_0: Mesh;
        Teacher_Desk_mat_metal_surface_0: Mesh;
        Teacher_Desk_mat_locks_handles_0: Mesh;
    };
    materials: {
        mat_leg_main: MeshStandardMaterial;
        mat_leg_foot: MeshStandardMaterial;
        mat_table_black: MeshStandardMaterial;
        mat_table_wood: MeshStandardMaterial;
        mat_metal_surface: MeshStandardMaterial;
        mat_locks_handles: MeshStandardMaterial;
    };
};

useGLTF.preload("/models/props/teachers_desk.glb");
