/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anom Purple Modelling (https://sketchfab.com/Anom404)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/painting-four-colors-b3f9d0e1bb72484d8a5c9d9c0f55a827
Title: Painting Four Colors
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshPhysicalMaterial } from "three";
import { GLTF } from "three-stdlib";

export const FourColorsPainting = () => {
    const model = useGLTF("/models/props/paintings/four_colors.glb") as GLTFResult;

    return (
        <>
            <primitive object={model.scene} position={[ -20.84, 1.5, -2 ]} rotation={[ 0, -Math.PI / 2, 0 ]} />
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        Plano001_Materiais003_0: Mesh;
    };
    materials: {
        ["Materiais.003"]: MeshPhysicalMaterial;
    };
};

useGLTF.preload("/models/props/paintings/four_colors.glb");
