/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anom Purple Modelling (https://sketchfab.com/Anom404)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/painting-four-colors-b3f9d0e1bb72484d8a5c9d9c0f55a827
Title: Painting Four Colors
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshPhysicalMaterial } from "three";
import { GLTF } from "three-stdlib";

export const ShadesOfBluePainting = () => {
    const model = useGLTF("/models/props/paintings/shades_of_blue.glb") as GLTFResult;

    return (
        <>
            <primitive object={ model.scene } position={ [ -3, 2, 0 ] } />
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        Plano001_Materiais001_0: Mesh;
    };
    materials: {
        ["Materiais.001"]: MeshPhysicalMaterial;
    };
};

useGLTF.preload("/models/props/paintings/shades_of_blue.glb");
