/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anom Purple Modelling (https://sketchfab.com/Anom404)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/sun-painting-d594e9d5b5914d538b2457daa9c6d738
Title: Sun Painting
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshPhysicalMaterial } from "three";
import { GLTF } from "three-stdlib";

export const SunPainting = () => {
    const model = useGLTF("/models/props/paintings/sun.glb") as GLTFResult;

    return (
        <>
            <primitive object={model.scene} position={[ 8.84, 1.5, 1 ]} rotation={[ 0, -Math.PI / 2, 0 ]} />
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        Plano001_Materiais003_0: Mesh;
    };
    materials: {
        ["Materiais.003"]: MeshPhysicalMaterial;
    };
};

useGLTF.preload("/models/props/paintings/sun.glb");
