/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nguyennghiakk (https://sketchfab.com/nguyennghiakk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/school-corridor-38bccd81e8bf416b8bccf7a2f595a916
Title: School Corridor
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { Mesh, MeshPhysicalMaterial, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

import { IAnomalyProps } from "@/models/props/props-interface";
import useGame from "@/store/useGame";

export const SchoolCorridor = ({ isAnomaly, anomalyType }: IAnomalyProps) => {
    const { difficulty } = useGame();

    const { nodes, materials } = useGLTF("/models/map/school_corridor.glb") as GLTFResult;

    const isAnomalyEasy1 = isAnomaly && difficulty === "easy" && anomalyType === 1;
    const isAnomalyEasy2 = isAnomaly && difficulty === "easy" && anomalyType === 2;
    const isAnomalyEasy3 = isAnomaly && difficulty === "easy" && anomalyType === 3;
    const isAnomalyEasy4 = isAnomaly && difficulty === "easy" && anomalyType === 4;
    const isAnomalyEasy5 = isAnomaly && difficulty === "easy" && anomalyType === 5;
    const isAnomalyHard1 = isAnomaly && difficulty === "hard" && anomalyType === 1;

    return (
        <group dispose={null} position={[ 0, 0, 0 ]} scale={0.5} visible={true}>
            <group position={[ -4.888, -9.716, 11.091 ]} rotation={[ -Math.PI, -0.948, -Math.PI ]}>
                <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials["Material.005"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials["Material.005"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials["Leaves.001"]} />
            </group>
            <group position={[ -29.043, -9.716, 11.306 ]} rotation={[ -Math.PI, -0.948, -Math.PI ]}>
                <mesh castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials["Material.005"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials["Material.005"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials["Leaves.001"]} />
            </group>
            <group position={[ -57.798, -9.716, 6.672 ]} rotation={[ -Math.PI, -0.948, -Math.PI ]}>
                <mesh castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials["Material.005"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials["Material.005"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_25.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_27.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_28.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_29.geometry} material={materials["Leaves.001"]} />
            </group>
            <RigidBody type="fixed">
                <group position={[ 0, -1.112, 2.96 ]} scale={[ 5.981, 0.034, 3 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_33.geometry} material={materials["Material.003"]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_34.geometry} material={materials["Material.004"]} />
                </group>
                <group position={[ 12, -1.111, 2.96 ]} scale={[ 5.981, 0.034, 3 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_33.geometry} material={materials["Material.003"]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_34.geometry} material={materials["Material.004"]} />
                </group>
                <group position={[ 0, 3.053, 6.785 ]} scale={[ 1, 4.196, 1 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_36.geometry} material={materials.tuongxanh} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_37.geometry} material={materials.Material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_38.geometry} material={materials["Material.003"]} />
                </group>
                <group position={[ 0, 6.89, 3.026 ]} scale={[ 1.662, 0.027, 0.108 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_46.geometry} material={materials.material_8} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_47.geometry} material={materials.den1} />
                </group>
                <group position={[ 12, 6.89, 3.026 ]} scale={[ 1.662, 0.027, 0.108 ]} visible={isAnomalyEasy1 ? false : true}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_46.geometry} material={materials.material_8} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_47.geometry} material={materials.den1} />
                </group>
            </RigidBody>
            <RigidBody type="fixed" position={[ -44.997, -1.04, -6.7 ]} rotation={[ 0, -Math.PI / 2, 0 ]}>
                <group scale={[ 6.69, 0.038, 3.355 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_59.geometry} material={materials["Material.003"]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_60.geometry} material={materials["Material.004"]} />
                </group>
            </RigidBody>
            <RigidBody type="fixed" position={[ -47.938, 6.307, 3.298 ]} rotation={[ Math.PI / 2, 0, Math.PI / 2 ]}>
                <group scale={[ 0.497, 0.035, 0.244 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_62.geometry} material={materials["Material.007"]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_63.geometry} material={materials.material_8} />
                </group>
            </RigidBody>
            <RigidBody type="fixed">
                <group position={[ -2.046, 0, 0 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_65.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_66.geometry} material={materials.kinh} />
                </group>
            </RigidBody>
            <RigidBody type="fixed" position={[ 2.018, 0, 0.006 ]} rotation={[ 0, 0.008, 0 ]}>
                <group scale={[ -1, 1, 1 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_68.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_69.geometry} material={materials.kinh} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_70.geometry} material={materials["Material.001"]} />
                </group>
            </RigidBody>
            <RigidBody type="fixed">
                <group position={[ 2.184, 1.95, 0 ]} scale={[ 0.192, 0.056, 0.147 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_72.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_73.geometry} material={materials.kinh} />
                </group>
                <group position={[ 2.183, 4.565, 0 ]} scale={[ 0.192, 0.033, 0.147 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_75.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_76.geometry} material={materials.kinh} />
                </group>
                <group position={isAnomalyEasy3 ? [ -11.981, 0, 0.006 ] : [ -14.046, 0, 0 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_78.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_79.geometry} material={materials.kinh} />
                </group>
                <group scale={[ -1, 1, 1 ]} position={isAnomalyEasy3 ? [ -11.94, 0, 0 ] : [ -9.981, 0, 0.006 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_81.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_82.geometry} material={materials.kinh} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_83.geometry} material={materials["Material.001"]} />
                </group>
            </RigidBody>
            <RigidBody type="fixed">
                <group position={[ -9.815, 1.95, 0 ]} scale={[ 0.192, 0.056, 0.147 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_85.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_86.geometry} material={materials.kinh} />
                </group>
                <group position={[ -9.816, 4.565, 0 ]} scale={[ 0.192, 0.033, 0.147 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_88.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_89.geometry} material={materials.kinh} />
                </group>
                <group position={[ -25.987, 0, 0 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_91.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_92.geometry} material={materials.kinh} />
                </group>
            </RigidBody>
            <RigidBody type="fixed" position={[ -21.923, 0, 0.006 ]} rotation={[ 0, 0.035, 0 ]}>
                <group scale={[ -1, 1, 1 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_94.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_95.geometry} material={materials.kinh} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_96.geometry} material={materials["Material.001"]} />
                </group>
            </RigidBody>
            <RigidBody type="fixed">
                <group position={[ -21.756, 1.95, 0 ]} scale={[ 0.192, 0.056, 0.147 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_98.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_99.geometry} material={materials.kinh} />
                </group>
                <group position={[ -21.758, 4.565, 0 ]} scale={[ 0.192, 0.033, 0.147 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_101.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_102.geometry} material={materials.kinh} />
                </group>
                <group position={[ -37.952, 0, 0 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_104.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_105.geometry} material={materials.kinh} />
                </group>
            </RigidBody>
            <RigidBody type="fixed" position={[ -33.887, 0, 0.006 ]} rotation={[ 0, 0.008, 0 ]}>
                <group scale={[ -1, 1, 1 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_107.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_108.geometry} material={materials.kinh} />
                    <mesh visible={isAnomalyEasy4 ? false : true} castShadow receiveShadow geometry={nodes.Object_109.geometry} material={materials["Material.001"]} />
                </group>
            </RigidBody>
            <RigidBody type="fixed">
                <group position={[ -33.721, 1.95, 0 ]} scale={[ 0.192, 0.056, 0.147 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_111.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_112.geometry} material={materials.kinh} />
                </group>
                <group position={[ -33.722, 4.565, 0 ]} scale={[ 0.192, 0.033, 0.147 ]}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_114.geometry} material={materials.material} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_115.geometry} material={materials.kinh} />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_31.geometry}
                    material={materials.Material}
                    position={[ 0, 2.983, -0.269 ]}
                    scale={[ 5.981, 4.002, 0.261 ]}
                />
                <mesh castShadow receiveShadow material={isAnomalyEasy5 ? materials["Material.004"] : materials.Material} rotation={[ 0, -Math.PI / 2, 0 ]} position={[ 12, 2.9, -0.26 ]}>
                    <boxGeometry args={[ 0.5, 8, 12.1 ]} />
                </mesh>
            </RigidBody>
            <RigidBody type="fixed">
                <mesh castShadow receiveShadow material={materials.Material} rotation={[ -Math.PI / 2, 0, 0 ]} position={[ 18, 2.9, 3 ]}>
                    <boxGeometry args={[ 0.5, 7, 8 ]} />
                </mesh>
            </RigidBody>
            <RigidBody type="fixed" position={[ 0, 1.614, 6.024 ]} rotation={[ 0, 0, -Math.PI / 2 ]}>
                <mesh castShadow receiveShadow geometry={nodes.Object_40.geometry} material={materials.material} scale={[ 0.08, 5.37, 0.08 ]} />
                <mesh
                    position={[ 0, 12, 0 ]}
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_40.geometry}
                    material={materials.material}
                    scale={[ 0.08, 5.37, 0.08 ]}
                />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_42.geometry}
                    material={materials.Material}
                    position={[ 0, 6.936, 2.96 ]}
                    scale={[ 5.981, 0.034, 3 ]}
                />
                <mesh castShadow receiveShadow geometry={nodes.Object_44.geometry} material={materials.material_0} position={[ 4.913, 0, -1.481 ]} />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_49.geometry}
                    material={materials.material_0}
                    position={[ -50.803, 3.99, 6.027 ]}
                    scale={[ 2.454, 2.701, 0.107 ]}
                />
            </RigidBody>
            <RigidBody type="fixed" colliders="trimesh">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_51.geometry}
                    material={materials.tuongxanh}
                    position={[ -53.437, -0.118, 0 ]}
                    scale={[ 0.319, 1, 1 ]}
                />
            </RigidBody>
            <RigidBody type="fixed" position={[ -53.564, 1.48, 2.833 ]} rotation={[ 0, isAnomalyEasy2 ? Math.PI / 2 : -Math.PI / 2, 0 ]}>
                <mesh castShadow receiveShadow geometry={nodes.Object_53.geometry} material={materials.Material} scale={[ 2.193, 0.046, 0.172 ]} />
            </RigidBody>
            <RigidBody type="fixed">
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_55.geometry}
                    material={materials.material_0}
                    position={[ -45.448, 1.573, 6.106 ]}
                    scale={[ 2.978, 0.046, 0.172 ]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_57.geometry}
                    material={materials["Material.002"]}
                    position={[ 0, 6.363, 0.386 ]}
                    scale={[ 5.981, 0.166, 0.283 ]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_57.geometry}
                    material={materials["Material.002"]}
                    position={[ 12, 6.363, 0.386 ]}
                    scale={[ 5.981, 0.166, 0.283 ]}
                />
            </RigidBody>
            {/* Custom */}
            <RigidBody type="fixed">
                <mesh position={[ -48.365, 2.65, -9.2 ]} material={materials.tuongxanh}>
                    <boxGeometry args={[ 0.215, 7.64, 8.5 ]} />
                </mesh>
            </RigidBody>
            <RigidBody type="fixed">
                <mesh position={[ -48.365, 6.6, -6.7 ]} material={materials.tuongxanh}>
                    <boxGeometry args={[ 0.215, 0.33, 13.5 ]} />
                </mesh>
            </RigidBody>
            <RigidBody type="fixed">
                <mesh position={[ -41.565, 2.9, -10.7 ]} material={materials.material_0}>
                    <boxGeometry args={[ 0.215, 8, 5.4 ]} />
                </mesh>
            </RigidBody>
            <mesh position={[ -45, 6.8, -6.7 ]} material={materials.Material}>
                <boxGeometry args={[ 6.8, 0.33, 13.5 ]} />
            </mesh>
            <group position={[ -57.798, -9.716, -3.5 ]} visible={isAnomalyHard1 ? true : false}>
                <mesh castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials["Material.005"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials["Material.005"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_25.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_27.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_28.geometry} material={materials["Leaves.001"]} />
                <mesh castShadow receiveShadow geometry={nodes.Object_29.geometry} material={materials["Leaves.001"]} />
            </group>
        </group>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        Object_4: Mesh;
        Object_5: Mesh;
        Object_7: Mesh;
        Object_8: Mesh;
        Object_9: Mesh;
        Object_10: Mesh;
        Object_11: Mesh;
        Object_13: Mesh;
        Object_14: Mesh;
        Object_16: Mesh;
        Object_17: Mesh;
        Object_18: Mesh;
        Object_19: Mesh;
        Object_20: Mesh;
        Object_22: Mesh;
        Object_23: Mesh;
        Object_25: Mesh;
        Object_26: Mesh;
        Object_27: Mesh;
        Object_28: Mesh;
        Object_29: Mesh;
        Object_31: Mesh;
        Object_33: Mesh;
        Object_34: Mesh;
        Object_36: Mesh;
        Object_37: Mesh;
        Object_38: Mesh;
        Object_40: Mesh;
        Object_42: Mesh;
        Object_44: Mesh;
        Object_46: Mesh;
        Object_47: Mesh;
        Object_49: Mesh;
        Object_51: Mesh;
        Object_53: Mesh;
        Object_55: Mesh;
        Object_57: Mesh;
        Object_59: Mesh;
        Object_60: Mesh;
        Object_62: Mesh;
        Object_63: Mesh;
        Object_65: Mesh;
        Object_66: Mesh;
        Object_68: Mesh;
        Object_69: Mesh;
        Object_70: Mesh;
        Object_72: Mesh;
        Object_73: Mesh;
        Object_75: Mesh;
        Object_76: Mesh;
        Object_78: Mesh;
        Object_79: Mesh;
        Object_81: Mesh;
        Object_82: Mesh;
        Object_83: Mesh;
        Object_85: Mesh;
        Object_86: Mesh;
        Object_88: Mesh;
        Object_89: Mesh;
        Object_91: Mesh;
        Object_92: Mesh;
        Object_94: Mesh;
        Object_95: Mesh;
        Object_96: Mesh;
        Object_98: Mesh;
        Object_99: Mesh;
        Object_101: Mesh;
        Object_102: Mesh;
        Object_104: Mesh;
        Object_105: Mesh;
        Object_107: Mesh;
        Object_108: Mesh;
        Object_109: Mesh;
        Object_111: Mesh;
        Object_112: Mesh;
        Object_114: Mesh;
        Object_115: Mesh;
    };
    materials: {
        ["Material.005"]: MeshStandardMaterial;
        ["Leaves.001"]: MeshStandardMaterial;
        Material: MeshStandardMaterial;
        ["Material.003"]: MeshStandardMaterial;
        ["Material.004"]: MeshStandardMaterial;
        tuongxanh: MeshStandardMaterial;
        material: MeshStandardMaterial;
        material_0: MeshStandardMaterial;
        material_8: MeshStandardMaterial;
        den1: MeshStandardMaterial;
        ["Material.002"]: MeshStandardMaterial;
        ["Material.007"]: MeshStandardMaterial;
        kinh: MeshPhysicalMaterial;
        ["Material.001"]: MeshStandardMaterial;
    };
};

useGLTF.preload("/models/map/school_corridor.glb");
