/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sousinho (https://sketchfab.com/sousinho)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/steel-bin-fa1519af612e41ec9f1710820cd3b243
Title: Steel bin
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

import { IAnomalyProps } from "@/models/props/props-interface";
import useGame from "@/store/useGame";

export const SteelBin = ({ isAnomaly, anomalyType }: IAnomalyProps) => {
    const { difficulty } = useGame();

    const model = useGLTF("/models/props/bins/steel.glb") as GLTFResult;

    const isAnomalyHard1 = isAnomaly && difficulty === "hard" && anomalyType === 1;

    return (
        <>
            <primitive object={model.scene} position={[ -19, -0.604, -0.6 ]} scale={1.3} visible={isAnomalyHard1 ? false : true} />
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        SM_bin_T_bin_0: Mesh;
    };
    materials: {
        T_bin: MeshStandardMaterial;
    };
};

useGLTF.preload("/models/props/bins/steel.glb");
