/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Modelified (https://sketchfab.com/modelified)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/backpack-942d8c56ceeb43b585df40702875a9d8
Title: Backpack
*/

import { Clone, useGLTF } from "@react-three/drei";
import { useMemo, useRef } from "react";
import { Euler, Group, Mesh, MeshStandardMaterial, Vector3 } from "three";
import { GLTF } from "three-stdlib";

export const BackpackBrown = () => {
    const model = useGLTF("/models/props/backpacks/brown.glb") as GLTFResult;

    const backpackRef = useRef<Group>(null);

    const backpacks = useMemo(() => {
        return [ { position: new Vector3(-4.8, -0.255, -2.8), rotation: new Euler(0, 0, 0) } ];
    }, []);

    return (
        <>
            {backpacks.map((backpack, index) => (
                <Clone key={ index } ref={ backpackRef } object={ model.scene } scale={ 1.5 } rotation={ backpack.rotation } position={ backpack.position } />
            ))}
        </>
    );
};

type GLTFResult = GLTF & {
    nodes: {
        g0: Mesh;
    };
    materials: {
        material: MeshStandardMaterial;
    };
};

useGLTF.preload("/models/props/backpacks/brown.glb");
