/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import { useEffect, useMemo, useRef } from "react";
import { AnimationClip, Bone, Group, MeshStandardMaterial, SkinnedMesh } from "three";
import { GLTF, SkeletonUtils } from "three-stdlib";

export function Michelle(props: React.JSX.IntrinsicElements["group"]) {
    const group = useRef<Group>(null);

    const { scene, animations } = useGLTF("/models/entities/michelle.glb") as GLTFResult;
    const clone = useMemo(() => SkeletonUtils.clone(scene), [ scene ]);

    const { nodes, materials } = useGraph(clone) as GLTFResult;

    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        actions.Sitting_idle && actions.Sitting_idle.play();
    }, [ actions.Sitting_idle ]);

    return (
        <group ref={group} {...props} dispose={null} position={[ -14.2, -0.55, -3.3 ]} rotation={[ 0, -Math.PI / 2, 0 ]} scale={1.2}>
            <group name="Scene">
                <group name="Armature" rotation={[ Math.PI / 2, 0, 0 ]} scale={0.01}>
                    <primitive object={nodes.mixamorigHips} />
                </group>
                <skinnedMesh name="Ch03" geometry={nodes.Ch03.geometry} material={materials.Ch03_Body} skeleton={nodes.Ch03.skeleton} rotation={[ Math.PI / 2, 0, 0 ]} scale={0.01} />
            </group>
        </group>
    );
}

type TActionName = "Sitting_idle" | "T-pose";

interface IGLTFAction extends AnimationClip {
    name: TActionName;
}

type GLTFResult = GLTF & {
    nodes: {
        Ch03: SkinnedMesh;
        mixamorigHips: Bone;
    };
    materials: {
        Ch03_Body: MeshStandardMaterial;
    };
    animations: IGLTFAction[];
};

useGLTF.preload("/models/entities/michelle.glb");
